#!/usr/bin/env bash
# Bash script that prints Best School repeatedly
N=1
while [ "$N" -lt 11 ]; 
do
	if [ "$N" -ne 9 ]
	then
		echo "Best School"
	else
		echo "Best School"
		echo "Hi"
	fi
	((N++));
done
