#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes
#   display hours from 0 to 12
#   display minutes from 1 to 59
hours=0
mins=1
while [ "$hours" -lt 13 ]
do
  echo "Hour: $hours"
  while [ "$mins" -lt 60 ]
  do
	  echo "$mins"
	  ((mins++))
  done
  (( hours++ ))
  mins=1
done
